-- MySQL Script generated by MySQL Workbench
-- Mon Aug 14 15:18:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mq20175097
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mq20175097
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mq20175097` DEFAULT CHARACTER SET utf8 ;
USE `mq20175097` ;

-- -----------------------------------------------------
-- Table `mq20175097`.`Musician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Musician` (
  `SSN` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone_no` VARCHAR(10) NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mq20175097`.`Instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Instrument` (
  `InstrumentID` INT NOT NULL,
  `Instrument_Name` VARCHAR(45) NULL,
  `Musical_key` VARCHAR(10) NULL,
  PRIMARY KEY (`InstrumentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mq20175097`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Album` (
  `Album_Identifier` INT NOT NULL,
  `Album_title` VARCHAR(45) NULL,
  `Copyright_date` DATE NULL,
  `format` VARCHAR(10) NULL,
  `Musician_SSN` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Album_Identifier`),
  INDEX `fk_Album_Musician1_idx` (`Musician_SSN` ASC),
  CONSTRAINT `fk_Album_Musician1`
    FOREIGN KEY (`Musician_SSN`)
    REFERENCES `mq20175097`.`Musician` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mq20175097`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Song` (
  `SongID` INT NOT NULL,
  `Song_title` VARCHAR(45) NULL,
  `Composer_name` VARCHAR(45) NULL,
  `Author_name` VARCHAR(45) NULL,
  `Album_Album_Identifier` INT NOT NULL,
  PRIMARY KEY (`SongID`),
  INDEX `fk_Song_Album_idx` (`Album_Album_Identifier` ASC),
  CONSTRAINT `fk_Song_Album`
    FOREIGN KEY (`Album_Album_Identifier`)
    REFERENCES `mq20175097`.`Album` (`Album_Identifier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mq20175097`.`Performs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Performs` (
  `Musician_SSN` VARCHAR(10) NOT NULL,
  `Song_SongID` INT NOT NULL,
  PRIMARY KEY (`Musician_SSN`, `Song_SongID`),
  INDEX `fk_Musician_has_Song_Song1_idx` (`Song_SongID` ASC),
  INDEX `fk_Musician_has_Song_Musician1_idx` (`Musician_SSN` ASC),
  CONSTRAINT `fk_Musician_has_Song_Musician1`
    FOREIGN KEY (`Musician_SSN`)
    REFERENCES `mq20175097`.`Musician` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musician_has_Song_Song1`
    FOREIGN KEY (`Song_SongID`)
    REFERENCES `mq20175097`.`Song` (`SongID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mq20175097`.`Plays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mq20175097`.`Plays` (
  `Musician_SSN` VARCHAR(10) NOT NULL,
  `Instrument_InstrumentID` INT NOT NULL,
  `years_of_experience` INT NULL,
  PRIMARY KEY (`Musician_SSN`, `Instrument_InstrumentID`),
  INDEX `fk_Musician_has_Instrument_Instrument1_idx` (`Instrument_InstrumentID` ASC),
  INDEX `fk_Musician_has_Instrument_Musician1_idx` (`Musician_SSN` ASC),
  CONSTRAINT `fk_Musician_has_Instrument_Musician1`
    FOREIGN KEY (`Musician_SSN`)
    REFERENCES `mq20175097`.`Musician` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musician_has_Instrument_Instrument1`
    FOREIGN KEY (`Instrument_InstrumentID`)
    REFERENCES `mq20175097`.`Instrument` (`InstrumentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
